# Trading Model {#trading-todel}

## Model Specification

We implement a very simple version of a common systematic trend-following strategy [@Faith2007-cf]\footnote{See the reference for the definition of the EMA}. The instrument-level logic of the trading system has a several core components: 1) The *entry signal*, determines timing for initiating a position (either long or short) in a particular instrument; 2) The *position sizing* algorithm determines the size of a position; and, 3) The *trailing stop loss* determines the timing of a exit from a position\footnote{Although trend-following models used in practice have a layer of controls at the portfolio level, in this paper we focus only on the instrument-level components of the strategy.}. 

Both the position size and the distance of the trailing stop from the current price level are functions of the true range, $R_{t}$ (defined in Chapter \@ref(intro), Equation \@ref(eq:introTrueRange)).

Filters are commonly used to smooth price series. We use exponentially weighted moving averages (EMAs) to smooth both price and the true range time series.

The core rules of our simple trading model are detailed briefly in the next two sub-sections.

### Long Position

At $t$, if the fast $\text{EMA}_{t-1,F}$ is *above* the slow $\text{EMA}_{t-1,S}$ and we have no position, we enter a *long* position of $p_{t}$ units:

\begin{equation}
  p_{t}=\text{floor}\bigg[\frac{ f \times A_{t-1}}{\text{max}[\text{ATR}_{t-1} \times M,L]}\bigg]
  (\#eq:tradingModelLongPositionSizing)
\end{equation} 

where $f$ is the fraction of account size plus accrued realized P&L, $A$, risked per bet, $\text{ATR}_{t-1}$ is the EMA of the true range for the previous time step, $M$ is the risk multiplier, and $L$ is the $\text{ATR}$ floor.

We set our initial stop loss level $M$ units of ATR *below* the entry price level, $p_{t}$. For each subsequent time, $t$, we update our stop level as follows:

\begin{equation}
  s_{t}=\text{max}[P_{t}-\text{ATR}_{t-1} \times M,s_{t-1}]
  (\#eq:tradingModelLongStop)
\end{equation} 

We exit our long position if the price, $p_{t}$ moves below the stop loss level, $s_{t-1}$. 

### Short Position

At $t$, if the fast $\text{EMA}_{t-1,F}$ is *below* the slow $\text{EMA}_{t-1,S}$ and we have no position, we enter a *short* position of $p_{t}$ units:

\begin{equation}
  p_{t}=-\text{floor}\bigg[\frac{ f \times A_{t-1}}{\text{max}[\text{ATR}_{t-1} \times M,L]}\bigg]
  (\#eq:tradingModelShortPositionSizing)
\end{equation}

We set our initial stop loss level $M$ units of ATR *above* the entry price level, $p_{t}$. For each subsequent time, $t$, we update our stop level as follows:

\begin{equation}
  S_{t}=\text{min}[P_{t}-\text{ATR}_{t-1} \times M,S_{t-1}]
  (\#eq:tradingModelShortStop)
\end{equation} 

Regardless of whether we are long or short, for each trade we budget for a loss of $f$ percent of our account size plus accrued realized P&L. The effectiveness of this crude risk budgeting system is a function of the characteristics of the true range. Serial dependence in the true range can transform this simple mechanism from a feedback control to a feed-forward control. 

## Parameter Selection
